- name: Install dependencies (zsh and git)
  ansible.builtin.package:
    name:
      - zsh
      - git
    state: present
  become: yes
  become_user: "{{ target_user }}"

- name: Clone Oh My Zsh repository
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "/home/{{ target_user }}/.oh-my-zsh"
    version: master
    force: yes
  become: yes
  become_user: "{{ target_user }}"

- name: Set Zsh as the default shell for the target user
  ansible.builtin.user:
    name: "{{ target_user }}"
    shell: /usr/bin/zsh
  become: yes
  become_user: root

- name: Copy the .zshrc template to the target user's home directory
  ansible.builtin.copy:
    src: "/home/{{ target_user }}/.oh-my-zsh/templates/zshrc.zsh-template"
    dest: "/home/{{ target_user }}/.zshrc"
    mode: '0644'
  become: yes
  become_user: "{{ target_user }}"

- name: Ensure .zshrc is sourced for the target user
  ansible.builtin.lineinfile:
    path: "/home/{{ target_user }}/.zshrc"
    line: 'export ZSH="$HOME/.oh-my-zsh"'
    state: present
  become: yes
  become_user: "{{ target_user }}"
