- name: Install dependencies for RVM
  ansible.builtin.package:
    name:
      - curl
      - git
      - openssl
      - readline
      - zlib
      - gnupg
    state: present

- name: Import RVM GPG keys
  ansible.builtin.shell: |
    gpg2 --keyserver hkp://keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB || \
    (curl -sSL https://rvm.io/mpapis.asc | gpg2 --import - && \
    curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -)
  args:
    creates: "/home/{{ target_user }}/.gnupg/pubring.kbx"  # Skip if GPG keys are already imported
  become: yes
  become_user: "{{ target_user }}"

- name: Install RVM
  ansible.builtin.shell: |
    curl -sSL https://get.rvm.io | bash -s stable
  args:
    creates: "/home/{{ target_user }}/.rvm/bin/rvm"  # Skip if RVM is already installed
  become: yes
  become_user: "{{ target_user }}"

- name: Install Ruby (optional)
  ansible.builtin.shell: |
    timeout 300 bash -lc "rvm install ruby --autolibs=read-only"
  args:
    creates: "/home/{{ target_user }}/.rvm/rubies/ruby-*"  # Prevents reinstalling if Ruby is already installed
  become: yes
  become_user: "{{ target_user }}"

- name: Set default Ruby version (optional)
  ansible.builtin.shell: |
    bash -lc "rvm use ruby --default"
  become: yes
  become_user: "{{ target_user }}"

- name: Add RVM to zshrc for the target user
  ansible.builtin.lineinfile:
    path: "/home/{{ target_user }}/.zshrc"
    line: '[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM'
    create: yes
    state: present
  become: yes
  become_user: "{{ target_user }}"
