- name: kdenlive ppa (ppa:kdenlive/kdenlive-stable)
  become: true
  apt_repository:
    repo: ppa:kdenlive/kdenlive-stable
    state: present
    update_cache: True
  tags:
    - install
    - tools

- name: shutter ppa (ppa:linuxuprising/shutter)
  become: true
  apt_repository:
    repo: ppa:linuxuprising/shutter
    state: present
    update_cache: True
  tags:
    - install
    - tools

- name: peek ppa (ppa:peek-developers/stable)
  become: true
  apt_repository:
    repo: ppa:peek-developers/stable
    state: present
    update_cache: True
  tags:
    - install
    - tools

- name: redshift ppa (ppa:dobey/redshift-daily)
  become: true
  apt_repository:
    repo: ppa:dobey/redshift-daily
    state: present
    update_cache: True
  tags:
    - install
    - tools

- name: Clone dragon
  ansible.builtin.git:
    repo: 'https://github.com/mwh/dragon'
    dest: "{{ lookup('env', 'HOME') }}/Downloads/dragon"
- name: Build dragon
  shell: "cd {{ lookup('env', 'HOME') }}/dragon && make PREFIX={{ lookup('env', 'HOME') }}/.local/bin"
  tags:
    - install
    - dragon
    - tools

- name: required libraries for keynav
  become: true
  apt:
    name: ["libcairo2-dev", "libxinerama-dev", "libxdo-dev"]
  tags:
    - keynav
    - install
- name: Clone keynav
  ansible.builtin.git:
    repo: 'https://github.com/jordansissel/keynav'
    dest: "{{ lookup('env', 'HOME') }}/Downloads/keynav"
- name: Build keynav
  shell: "cd {{ lookup('env', 'HOME') }}/keynav && make install"
  tags:
    - install
    - keynav
    - tools

- name: Install packages
  become: true
  apt:
    name: [
        "mpv", # https://mpv.io/
        "httpie", # https://httpie.io/
        "wget", # https://github.com/mirror/wget
        "fd-find", # https://github.com/sharkdp/fd # ln -s $(which fdfind) ~/.local/bin/fd
        "gh", # https://cli.github.com/
        "surfraw", # http://surfraw.org/
        "redshift", # https://wiki.archlinux.org/title/Redshift
        "asciinema", # https://asciinema.org/
        "peek", # https://github.com/phw/peek
        "tmux", # https://github.com/tmux/tmux
        "wireshark", # https://www.wireshark.org/
        "fzf", # https://github.com/junegunn/fzf
        "kdenlive", # https://kdenlive.org/en/
        "krita", # https://krita.org/en/
        "gimp", # https://www.gimp.org/
        "xclip", # https://github.com/astrand/xclip
        "screenkey", # https://gitlab.com/screenkey/screenkey
        "tldr", # https://github.com/tldr-pages/tldr
        "ripgrep", # https://github.com/BurntSushi/ripgrep
        "shutter", # https://shutter-project.org/
        "tidy", # http://www.html-tidy.org/
        "fd-find", # https://github.com/sharkdp/fd
        "newsboat", # https://github.com/newsboat/newsboat
        "cobang", # https://github.com/hongquan/CoBang
        "htop", # https://github.com/htop-dev/htop
      ]
  tags:
    - install
    - tools
