- name: kdenlive ppa (ppa:kdenlive/kdenlive-stable)
  become: true
  apt_repository:
    repo: ppa:kdenlive/kdenlive-stable
    state: present
    update_cache: True
  tags:
    - install
    - tools

- name: shutter ppa (ppa:linuxuprising/shutter)
  become: true
  apt_repository:
    repo: ppa:linuxuprising/shutter
    state: present
    update_cache: True
  tags:
    - install
    - tools

- name: peek ppa (ppa:peek-developers/stable)
  become: true
  apt_repository:
    repo: ppa:peek-developers/stable
    state: present
    update_cache: True
  tags:
    - install
    - tools

- name: redshift ppa (ppa:dobey/redshift-daily)
  become: true
  apt_repository:
    repo: ppa:dobey/redshift-daily
    state: present
    update_cache: True
  tags:
    - install
    - tools

- name: Install packages
  become: true
  apt:
    name: [
        "httpie", # https://httpie.io/
        "fd-find", # https://github.com/sharkdp/fd # ln -s $(which fdfind) ~/.local/bin/fd
        "gh", # https://cli.github.com/
        "surfraw", # http://surfraw.org/
        "redshift", # https://wiki.archlinux.org/title/Redshift
        "asciinema", # https://asciinema.org/
        "peek", # https://github.com/phw/peek
        "tmux", # https://github.com/tmux/tmux
        "wireshark", # https://www.wireshark.org/
        "fzf", # https://github.com/junegunn/fzf
        "kdenlive", # https://kdenlive.org/en/
        "krita", # https://krita.org/en/
        "gimp", # https://www.gimp.org/
        "xclip", # https://github.com/astrand/xclip
        "screenkey", # https://gitlab.com/screenkey/screenkey
        "tldr", # https://github.com/tldr-pages/tldr
        "ripgrep", # https://github.com/BurntSushi/ripgrep
        "shutter", # https://shutter-project.org/
        "tidy", # http://www.html-tidy.org/
        "fd-find", # https://github.com/sharkdp/fd
      ]
  tags:
    - install
    - tools
